### ISSUE TITLE
Tests failing in python 3.5 and 3.6

### ISSUE THREAD

**Issue by overshard** [pinry/pinry#119]
Due to factory-boy, probably need to upgrade this dependency

**Comment by lapo-luchini** [comment]
Is that the cause of this?

```
Traceback (most recent call last):
  File "/usr/home/pinry/demo/core/tests/views.py", line 15, in setUp
    self.user = UserFactory(password='password')
  File "/home/pinry/.local/share/virtualenvs/demo-HyumSaMf/lib/python3.6/site-packages/factory/base.py", line 258, in __new__
    raise RuntimeError('You cannot instantiate BaseFactory')
RuntimeError: You cannot instantiate BaseFactory
```

(I'm trying to create an updated demo website, which could also help me upgrade my own install in the future)

**Comment by winkidney** [comment]
Working now, we use DRF instead of FactoryBoy and Tastypie.
