### ISSUE TITLE
[question] Default login

### ISSUE THREAD

**Issue by tit1** [pinry/pinry#145]
Morning.. 
Running this in docker on an ubuntu server 18.04.2 LTS. Docker image starts up fine and i am able to access the page but the issue i'm having is im not finding what the default username/password is for the django admin panel is. I saw in this issue #138 that you said the system should ask for a new user name and password on startup but that does not seem to be happening. I stoped the docker instance, removed `production.db` and restated. The database was re-created but still no startup screen. 

The instructions i followed for install where from here: https://github.com/pinry/docker-pinry

Many thanks

**Comment by winkidney** [comment]
Thanks for your feedback, just register a new user in pinry's home page (without any admin access).

If you want to create a superuser, you have to create it in django's management shell with `python manage.py createsuperuser`.

**Comment by tit1** [comment]
Thanks that worked. I did have to connected to the docker container's bash to run the script but it worked great..

**Comment by MaestroJAL** [comment]
Sorry to reopen this issue but I'm receiving this error executing the command within the Docker container:
Traceback (most recent call last):
  File "manage.py", line 13, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/usr/local/lib/python3.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python3.7/site-packages/django/apps/config.py", line 94, in create
    module = import_module(entry)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'django_extensions'

**Comment by winkidney** [comment]
Hi,
You have two options to resolve this behavior:

**Comment by winkidney** [comment]
The doc will be updated later.

**Comment by winkidney** [comment]
Updated here: https://docs.getpinry.com/passwords/
Feel free to reopen it if have have any further problem.
