### ISSUE TITLE
Dumping and loading `core` does not work?（higher django version had been fixed this issue）

### ISSUE THREAD

**Issue by lapo-luchini** [pinry/pinry#210]
It might be something with my environment, but during a huge upgrade attept I noticed this:

```
% pipenv run python manage.py dumpdata core > db-backup.core2.json
/home/pinry/.local/share/virtualenvs/pinry-vuovyYpu/lib/python3.7/site-packages/django/core/management/commands/dumpdata.py:155: ProxyModelWarning: core.Image is a proxy model and won't be serialized.
  category=ProxyModelWarning,
% pipenv run python manage.py loaddata db-backup.core.json
Traceback (most recent call last):
  File "/home/pinry/.local/share/virtualenvs/pinry-vuovyYpu/lib/python3.7/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
  File "/home/pinry/.local/share/virtualenvs/pinry-vuovyYpu/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 326, in execute
    return Database.Cursor.execute(self, query)
sqlite3.OperationalError: no such table: django_images_image__old                                   
```

**Comment by lapo-luchini** [comment]
Same goes with `make backup-all ; make recover-all`.
(I'm trying with c285c236e3fb73c4e0265326481eee71ffa35beb)

**Comment by lapo-luchini** [comment]
Also happens on current master. (de0a1fa74b353a9870cf7fbd651e03f881414066)

**Comment by lapo-luchini** [comment]
Happens with SQLite 3.26.0+.

Can be solved [applying this simple patch](https://github.com/django/django/pull/11986/files) to django-1.11, which unfortunately wasn't accepted as backport (and was eventually solved in django2.1).

**Comment by winkidney** [comment]
We may should plan to upgrade our django version.

**Comment by winkidney** [comment]
closed via https://github.com/pinry/pinry/pull/218
