### ISSUE TITLE
Docker pinry - cant login

### ISSUE THREAD

**Issue by MWP** [pinry/pinry#255]
Hi all,

I've been battling this for a few hours now.
Im not new at all to linux server config, but I am new to using docker.

I've followed the docs...

"docker pull getpinry/pinry" - all good
"docker run -d=true -p=80:80 -v=/opt/docker-data/pinry:/data pinry/pinry"
This seemed to download the container again? should this be "getpinry/pinry" too?

Anyway, it appears to start fine. After that i can open the local pinry webpage, but i cant login.

So, first, i cant find a "local_settings.py" file anywhere? Docs dont say where it should be located?
I tried creating the file in "/opt/docker-data/pinry/local_settings.py", then restarting the docker container. No change.
So where should this go?

I also tried creating the superuser as noted on the "Updating Passwords" doc page.
I open a docker container shell using "docker exec -it <containername> /bin/bash".
I get:
root@17c4f0bede75:/srv/www/pinry# python manage.py createsuperuser --settings=pinry.settings.docker
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named django.core.management
root@17c4f0bede75:/srv/www/pinry#

So this is a bunch of fail so far.
... no wonder ive read some reports around the net of this being difficult to setup :(

Any help would be appreciated. Thanks.

**Comment by winkidney** [comment]
local_settings.py is located to your data folder.
I will try out our toturial again to reach your goal.
The doc will be updated, thanks.

**Comment by winkidney** [comment]
I have updated some description about local_settings.py.
The "pinry/pinry" has been fixed for a long time and not been released to our help site, now it has been fixed. 
Thanks for you feedback again.

**Comment by winkidney** [comment]
The password reset in docker has been updated:

```
# Inside Docker

If you use that command to create superuser inside docker, you could first exec to docker via command like `docker exec -it <container-id> bash` and then use `python manage.py createsuperuser --settings=pinry.settings.docker`

**Comment by winkidney** [comment]
Feel free to ask if you have any further problem.

I've tried to pull the docker container and start it, I could register a account by default and got all the settings file in my local data folder.

**Comment by MWP** [comment]
Oh wow, that's brilliant, thankyou.
I'll kill both my existing container and image, and start from scratch.
I'll report back how i go with it.
Thanks again.

**Comment by MWP** [comment]
No, go.

I did exactly this (logged in as root):
# mkdir /data/docker/pinry
# docker pull getpinry/pinry
# export DATA_PATH=/data/docker/pinry
# docker run -d=true -p=8120:80 -v=${DATA_PATH}:/data getpinry/pinry

The container dies shortly after being started.
Since the container was not named, it was given the name "silly_nobel".

# docker logs silly_nobel
.... trimmed
PermissionError: [Errno 13] Permission denied: '/pinry/pinry/settings/local_settings.py'
[2021-03-06 15:01:23 +0000] [26] [INFO] Worker exiting (pid: 26)
[2021-03-06 15:01:23 +0000] [29] [INFO] Booting worker with pid: 29
WARNING:root:No SECRET_KEY given in environ, please have a check.If you have a local_settings file, please ignore this warning.
[2021-03-06 15:01:23 +0000] [27] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/pinry/pinry/wsgi.py", line 4, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.7/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.7/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 79, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/pinry/pinry/settings/docker.py", line 40, in <module>
    from .local_settings import *
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 859, in get_code
  File "<frozen importlib._bootstrap_external>", line 916, in get_data
PermissionError: [Errno 13] Permission denied: '/pinry/pinry/settings/local_settings.py'
[2021-03-06 15:01:23 +0000] [27] [INFO] Worker exiting (pid: 27)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 202, in run
    self.manage_workers()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 545, in manage_workers
    self.spawn_workers()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 617, in spawn_workers
    time.sleep(0.1 * random.random())
  File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/gunicorn", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 58, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/base.py", line 228, in run
    super().run()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 229, in run
    self.halt(reason=inst.reason, exit_status=inst.exit_status)
  File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 342, in halt
    self.stop()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 393, in stop
    time.sleep(0.1)
  File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
WARNING:root:No SECRET_KEY given in environ, please have a check.If you have a local_settings file, please ignore this warning.

In /data/docker/pinry there are a bunch of files, but they have odd ownership.
Some are owned by root, others are owned by UID 1000 ?
Possibly where the permissions problem is coming from?

**Comment by winkidney** [comment]
Which is the user you use to start docker? 
What is your system? Linux (ubuntu, centos, etc)?
I use `sudo docker xxxxx` to run contianer and make data dir in my user-home (/home/winkidney/workspace/pinry).

If you still meet permission issue, I suggest that you use data-volume instead of local filesystem.

```
docker volume create pinry
docker run -d=true -p=80:80 \
    -v pinry:/data \
    getpinry/pinry
```

And then, edit all files in docker should be OK.

**Comment by MWP** [comment]
> Which is the user you use to start docker?
> What is your system? Linux (ubuntu, centos, etc)?
> I use `sudo docker xxxxx` to run contianer and make data dir in my user-home (/home/winkidney/workspace/pinry) and it works well.

I do everything logged in as root.
System is Debian Stretch x64.
 
> If you still meet permission issue, I suggest that you use data-volume instead of local filesystem.
> ```
> docker volume create pinry
> docker run -d=true -p=80:80 \
>     -v pinry:/data \
>     getpinry/pinry
> ```

That worked.
Interesting that a local volume worked ok, but a bind didnt. Hm.

Thanks again.
