### ISSUE TITLE
Unable to create user account

### ISSUE THREAD

**Issue by dasbootbee** [pinry/pinry#298]
Hello.  I can't create the initial user account.  I click register and nothing happens.  

Here is the log:

==================================================================================

Note: Please copy this key and keep it in a secure place.

Then you should manually edit your pinry/local_settings.py

and replace SECRET_KEY with new secret-key if you had previously generated a

pinry/local_settings.py.

If no previous pinry/local_settings.py generated, you can have a look and edit it.

If you want to use docker-compose, just edit docker-compose.yml and use 'docker-compose up'

Your secret-key is(also saved/overwritten your docker's /data/production_secret_key.txt):

REDACTED

==================================================================================

WARNING:root:No SECRET_KEY given in environ, please have a check.If you have a local_settings file, please ignore this warning.

153 static files copied to '/data/static'.

WARNING:root:No SECRET_KEY given in environ, please have a check.If you have a local_settings file, please ignore this warning.

Operations to perform:

  Apply all migrations: admin, auth, contenttypes, core, django_images, sessions, taggit, users

Running migrations:

Traceback (most recent call last):

  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 240, in _commit

    return self.connection.commit()

sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/recorder.py", line 67, in ensure_schema

    editor.create_model(self.Migration)

  File "/usr/local/lib/python3.7/site-packages/django/db/backends/sqlite3/schema.py", line 35, in __exit__

    super().__exit__(exc_type, exc_value, traceback)

  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/schema.py", line 112, in __exit__

    self.atomic.__exit__(exc_type, exc_value, traceback)

  File "/usr/local/lib/python3.7/site-packages/django/db/transaction.py", line 240, in __exit__

    connection.commit()

  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 262, in commit

    self._commit()

  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 240, in _commit

    return self.connection.commit()

  File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__

    raise dj_exc_value.with_traceback(traceback) from exc_value

  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 240, in _commit

    return self.connection.commit()

django.db.utils.OperationalError: database is locked

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "manage.py", line 13, in <module>

    execute_from_command_line(sys.argv)

  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line

    utility.execute()

  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute

    self.fetch_command(subcommand).run_from_argv(self.argv)

  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv

    self.execute(*args, **cmd_options)

  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute

    output = self.handle(*args, **options)

  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 83, in wrapped

    res = handle_func(*args, **kwargs)

  File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 234, in handle

    fake_initial=fake_initial,

  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/executor.py", line 91, in migrate

    self.recorder.ensure_schema()

  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/recorder.py", line 69, in ensure_schema

    raise MigrationSchemaMissing("Unable to create the django_migrations table (%s)" % exc)

django.db.migrations.exceptions.MigrationSchemaMissing: Unable to create the django_migrations table (database is locked)

[2021-09-10 18:35:47 +0000] [23] [INFO] Starting gunicorn 20.0.4

[2021-09-10 18:35:47 +0000] [23] [INFO] Listening at: http://0.0.0.0:8000 (23)

[2021-09-10 18:35:47 +0000] [23] [INFO] Using worker: sync

[2021-09-10 18:35:47 +0000] [26] [INFO] Booting worker with pid: 26

[2021-09-10 18:35:47 +0000] [27] [INFO] Booting worker with pid: 27

[2021-09-10 18:35:47 +0000] [28] [INFO] Booting worker with pid: 28

[2021-09-10 18:35:47 +0000] [29] [INFO] Booting worker with pid: 29

WARNING:root:No SECRET_KEY given in environ, please have a check.If you have a local_settings file, please ignore this warning.

WARNING:root:No SECRET_KEY given in environ, please have a check.If you have a local_settings file, please ignore this warning.

WARNING:root:No SECRET_KEY given in environ, please have a check.If you have a local_settings file, please ignore this warning.

WARNING:root:No SECRET_KEY given in environ, please have a check.If you have a local_settings file, please ignore this warning.

ERROR:django.request:Internal Server Error: /api/v2/pins/

Traceback (most recent call last):

  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute

    return self.cursor.execute(sql, params)

  File "/usr/local/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 383, in execute

    return Database.Cursor.execute(self, query, params)

sqlite3.OperationalError: no such table: core_pin

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner

    response = get_response(request)

  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response

    response = self.process_exception_by_middleware(e, request)

  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response

    response = wrapped_callback(request, *callback_args, **callback_kwargs)

  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view

    return view_func(*args, **kwargs)

  File "/usr/local/lib/python3.7/site-packages/rest_framework/viewsets.py", line 125, in view

    return self.dispatch(request, *args, **kwargs)

  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 509, in dispatch

    response = self.handle_exception(exc)

  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 469, in handle_exception

    self.raise_uncaught_exception(exc)

  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception

    raise exc

  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 506, in dispatch

    response = handler(request, *args, **kwargs)

  File "/usr/local/lib/python3.7/site-packages/rest_framework/mixins.py", line 40, in list

    page = self.paginate_queryset(queryset)

  File "/usr/local/lib/python3.7/site-packages/rest_framework/generics.py", line 171, in paginate_queryset

    return self.paginator.paginate_queryset(queryset, self.request, view=self)

  File "/usr/local/lib/python3.7/site-packages/rest_framework/pagination.py", line 379, in paginate_queryset

    self.count = self.get_count(queryset)

  File "/usr/local/lib/python3.7/site-packages/rest_framework/pagination.py", line 522, in get_count

    return queryset.count()

  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 392, in count

    return self.query.get_count(using=self.db)

  File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/query.py", line 504, in get_count

    number = obj.get_aggregation(using, ['__count'])['__count']

  File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/query.py", line 489, in get_aggregation

    result = compiler.execute_sql(SINGLE)

  File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1142, in execute_sql

    cursor.execute(sql, params)

  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute

    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)

  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers

    return executor(sql, params, many, context)

  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute

    return self.cursor.execute(sql, params)

  File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__

    raise dj_exc_value.with_traceback(traceback) from exc_value

  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute

    return self.cursor.execute(sql, params)

  File "/usr/local/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 383, in execute

    return Database.Cursor.execute(self, query, params)

django.db.utils.OperationalError: no such table: core_pin

ERROR:django.request:Internal Server Error: /api/v2/profile/users/

Traceback (most recent call last):

  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute

    return self.cursor.execute(sql, params)

  File "/usr/local/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 383, in execute

    return Database.Cursor.execute(self, query, params)

sqlite3.OperationalError: no such table: auth_user

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner

    response = get_response(request)

  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response

    response = self.process_exception_by_middleware(e, request)

  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response

    response = wrapped_callback(request, *callback_args, **callback_kwargs)

  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view

    return view_func(*args, **kwargs)

  File "/usr/local/lib/python3.7/site-packages/rest_framework/viewsets.py", line 125, in view

    return self.dispatch(request, *args, **kwargs)

  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 509, in dispatch

    response = self.handle_exception(exc)

  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 469, in handle_exception

    self.raise_uncaught_exception(exc)

  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception

    raise exc

  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 506, in dispatch

    response = handler(request, *args, **kwargs)

  File "/usr/local/lib/python3.7/site-packages/rest_framework/mixins.py", line 18, in create

    serializer.is_valid(raise_exception=True)

  File "/usr/local/lib/python3.7/site-packages/rest_framework/serializers.py", line 220, in is_valid

    self._validated_data = self.run_validation(self.initial_data)

  File "/usr/local/lib/python3.7/site-packages/rest_framework/serializers.py", line 419, in run_validation

    value = self.to_internal_value(data)

  File "/usr/local/lib/python3.7/site-packages/rest_framework/serializers.py", line 476, in to_internal_value

    validated_value = field.run_validation(primitive_value)

  File "/usr/local/lib/python3.7/site-packages/rest_framework/fields.py", line 799, in run_validation

    return super().run_validation(data)

  File "/usr/local/lib/python3.7/site-packages/rest_framework/fields.py", line 569, in run_validation

    self.run_validators(value)

  File "/usr/local/lib/python3.7/site-packages/rest_framework/fields.py", line 591, in run_validators

    validator(value, self)

  File "/usr/local/lib/python3.7/site-packages/rest_framework/validators.py", line 73, in __call__

    if qs_exists(queryset):

  File "/usr/local/lib/python3.7/site-packages/rest_framework/validators.py", line 21, in qs_exists

    return queryset.exists()

  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 766, in exists

    return self.query.has_results(using=self.db)

  File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/query.py", line 522, in has_results

    return compiler.has_results()

  File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1112, in has_results

    return bool(self.execute_sql(SINGLE))

  File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1142, in execute_sql

    cursor.execute(sql, params)

  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute

    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)

  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers

    return executor(sql, params, many, context)

  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute

    return self.cursor.execute(sql, params)

  File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__

    raise dj_exc_value.with_traceback(traceback) from exc_value

  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute

    return self.cursor.execute(sql, params)

  File "/usr/local/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 383, in execute

    return Database.Cursor.execute(self, query, params)

django.db.utils.OperationalError: no such table: auth_user

And here is my docker-compose:

version: '3'

services:
  pinry:
   image: getpinry/pinry
   container_name: pinry
   restart: unless-stopped
   ports:
    - "8084:80"
   volumes:
    - /mnt/nas/pinry:/data
   environment:
    - PUID=1001
    - PGID=998

Thanks in advance!

**Comment by winkidney** [comment]
It seems that the database is locked. just shutdown the docker image then restart it after a while.
Once you done, attach to the docker to see logs then give it back to me.

If no "database is locked" occurs, you will be able to register by yourself.

**Comment by dasbootbee** [comment]
Thanks for getting back to me.  Can we specify what user within the container runs the application?  I have my /data directory on my NAS and I need to be able to run the application as my "docker" user since that is what has permission to the mount.  Other projects have the ability to read an EUID environment variable and set it in the container.

**Comment by winkidney** [comment]
I advise you to use "Data Volume" instead of data directory mounted to docker on **NAS** device with **permission issue**

ref: https://docs.docker.com/engine/reference/commandline/volume_create/

I personally use docker volume to do the
