### ISSUE TITLE
Failed to log in due to unexpected error: Error: Request failed with status code 500

### ISSUE THREAD

**Issue by CreateWebNZ** [pinry/pinry#349]
Hi, when I try to login, I get the following error in the console:
api.js:208
Failed to log in due to unexpected error: Error: Request failed with status code 500
    at t.exports (createError.js:16:15)
    at t.exports (settle.js:17:12)
    at XMLHttpRequest.y (xhr.js:54:7)

And:

ModelForm.js:24
Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'error')
    at r (ModelForm.js:24:21)
    at ModelForm.js:37:9
    at Array.forEach (<anonymous>)
    at Object.o (ModelForm.js:28:37)
    at LoginForm.vue:82:1

It worked until recently and unfortunately I cannot reproduce how and when it started. I simply hadn't logged in for a while and when I tried again, it just occured. 
Docker behind apache proxy. Direct access over wireguard doesn't work either.
https://pins.createweb.uk/

**Comment by winkidney** [comment]
will have a look on it

**Comment by winkidney** [comment]
would you like provide your logs about the 500 error for me?
If you use docker version , please use following command to get the log.

```
# get the container id, find pinry's docker
sudo docker ps 

# get the log 
docker logs <container_id> >error.log 
```

the `error.log` is the log file, upload it to github and I wll have a look on it, thanks.

**Comment by CreateWebNZ** [comment]
Hi there,
I have it running in a docker container and copied the error message from my portainer installation:

ERROR:django.request:Internal Server Error: /api/v2/profile/login/
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/sqlite3/base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: authtoken_token
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/pinry/users/views.py", line 87, in login_user
    data = UserSerializer(
  File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 555, in data
    ret = super().data
  File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/fields.py", line 1886, in to_representation
    return method(value)
  File "/pinry/users/serializers.py", line 81, in get_token
    return create_token_if_necessary(obj).key
  File "/pinry/users/models.py", line 10, in create_token_if_necessary
    token = Token.objects.filter(user=user).first()
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 653, in first
    for obj in (self if self.ordered else self.order_by('pk'))[:1]:
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 274, in __iter__
    self._fetch_all()
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1142, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/sqlite3/base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: authtoken_token

It seems there is a db table "authtoken_token" missing. Is it possible that the table was introduced with an upgrade and somehow wasn't created in my installation?
If that's the problem, maybe you can provide me with a sql file and tell me where the db is located so I can migrate it?

**Comment by winkidney** [comment]
Yes, you could just  run `docker exec -it <container-id> bash` then run `poetry run ./manage.py migrate` to resolve thsi problem.

**Comment by CreateWebNZ** [comment]
Now I get "poetry: command not found"
And when I do `pip install poetry` and then `poetry run ./manage.py migrate` I get the following error:
```
  PermissionError

  [Errno 13] Permission denied: './manage.py'

  at /usr/local/lib/python3.9/os.py:597 in _execvpe
       593│         argrest = (args,)
       594│         env = environ
       595│ 
       596│     if path.dirname(file):
    →  597│         exec_func(file, *argrest)
       598│         return
       599│     saved_exc = None
       600│     path_list = get_exec_path(env)
       601│     if name != 'nt':
```

**Comment by winkidney** [comment]
> Now I get "poetry: command not found" And when I do `pip install poetry` and then `poetry run ./manage.py migrate` I get the following error:
> 
> ```
>   PermissionError
> 
>   [Errno 13] Permission denied: './manage.py'
> 
>   at /usr/local/lib/python3.9/os.py:597 in _execvpe
>        593│         argrest = (args,)
>        594│         env = environ
>        595│ 
>        596│     if path.dirname(file):
>     →  597│         exec_func(file, *argrest)
>        598│         return
>        599│     saved_exc = None
>        600│     path_list = get_exec_path(env)
>        601│     if name != 'nt':
> ```

Sorry, poetry is not required.
Just run `python ./manage.py migrate` is ok.

**Comment by winkidney** [comment]
New docker version of Pinry has no Poetry or Pipenv required.

**Comment by winkidney** [comment]
no further replay, closed.
feel free to reopen it if you have any problem.
