### ISSUE TITLE
Pininterest 

### ISSUE THREAD

**Issue by SheepDomination** [pinry/pinry#385]
Is it possible to download all images from pin interest ?

**Comment by jamesmandrews** [comment]
There hasn't been any development on this in 2 years, and there 14 pull requests that have been ignore, mostly from dependabot, I think this is abandoned, you might be better off forking it and adding the functionality yourself.

**Comment by SheepDomination** [comment]
> There hasn't been any development on this in 2 years, and there 14 pull requests that have been ignore, mostly from dependabot, I think this is abandoned, you might be better off forking it and adding the functionality yourself.

I was informed this could do it, but as you mentioned; I can't get a reply.

**Comment by jamesmandrews** [comment]
I am unsure, you may want to try and install it as a docker container and see what it offers.

**Comment by jamesmandrews** [comment]
I'll save you some effort.  I tried the docker image on dockerhub and the docker-compose in the repo, and couldn't easily get it started....

**Comment by 0xmex** [comment]
@jamesmandrews If it is still of interest: This repo has seen some commits in the past weeks. I am currently playing with Pinry on my Portainer installation and this is my compose file:

```yml
services:
  pinry:
    container_name: pinry
    hostname: pinry
    image: getpinry/pinry:latest
    networks:
      - my-net
    ports:
      - "127.0.0.1:2048:8000"
    environment:
      - SECRET_KEY=CHANGE-ME
      - DJANGO_SETTINGS_MODULE=pinry.settings.development
    user: ${CURRENT_UID}
    volumes:
      - /path/to/persist/folders/pinry/app/:/app
    restart: unless-stopped

networks:
  my-net:
    name: my-net
    external: true
```

However, even when it says it is listening on port 8000 (internally) I can't connect to it ...
This is the log output of the container:

```bash
Traceback (most recent call last):
  File "/pinry/manage.py", line 13, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/usr/local/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.9/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python3.9/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'django_extensions'
Traceback (most recent call last):
  File "/pinry/manage.py", line 13, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/usr/local/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.9/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python3.9/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'django_extensions'
[2025-03-22 13:39:01 +0000] [23] [INFO] Starting gunicorn 20.1.0
[2025-03-22 13:39:01 +0000] [23] [INFO] Listening at: http://0.0.0.0:8000 (23)
[2025-03-22 13:39:01 +0000] [23] [INFO] Using worker: sync
[2025-03-22 13:39:01 +0000] [24] [INFO] Booting worker with pid: 24
[2025-03-22 13:39:01 +0000] [25] [INFO] Booting worker with pid: 25
[2025-03-22 13:39:01 +0000] [26] [INFO] Booting worker with pid: 26
```

When opening up the website the reverse proxy is working, forwarding the call to the container. But then it doesn't find anything:

```
Not Found

The requested resource was not found on this server.
```

**Comment by TomK32** [comment]
@SheepDomination Pinterest has a function where you can request your data to download https://help.pinterest.com/en/article/download-your-pinterest-data

Days later you'll receive a single HTML file and the intern who wrote it clearly was given the same HTML book I learnt from in 1999 but still has to read beyond chapter 2. But it can be parsed into useful data for an importer. I'll report back once I find my Python 2.7 book from 2010 and start with an importer... ;-)

**Comment by SheepDomination** [comment]
> [@SheepDomination](https://github.com/SheepDomination) Pinterest has a function where you can request your data to download https://help.pinterest.com/en/article/download-your-pinterest-data
> 
> Days later you'll receive a single HTML file and the intern who wrote it clearly was given the same HTML book I learnt from in 1999 but still has to read beyond chapter 2. But it can be parsed into useful data for an importer. I'll report back once I find my Python 2.7 book from 2010 and start with an importer... ;-)

Alright, I look forward to it ;-)

**Comment by TomK32** [comment]
@SheepDomination The parser on my fork is taking the html and produces nice JSON output for the pins. Boards is possible if someone has too many of those. Anyone willing to take it from here?

**Comment by SheepDomination** [comment]
> [@SheepDomination](https://github.com/SheepDomination) The parser on my fork is taking the html and produces nice JSON output for the pins. Boards is possible if someone has too many of those. Anyone willing to take it from here?

It may be all for you :)

**Comment by TomK32** [comment]
> It may be all for you :)

As soon as I'm done with upgrading the app to vue3 et cetera
